package com.gauvain.seigneur.design.theme

import androidx.compose.ui.graphics.Color

// Light
val md_theme_light_primary = Color(0xFFFFFFFF)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFEADDFF)
val md_theme_light_onPrimaryContainer = Color(0xFF24005A)
val md_theme_light_secondary = Color(0xFF934B00)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFFDCC4)
val md_theme_light_onSecondaryContainer = Color(0xFF2F1400)
val md_theme_light_tertiary = Color(0xFF85468C)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFD6FD)
val md_theme_light_onTertiaryContainer = Color(0xFF36003E)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF1C1B1E)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF1C1B1E)
val md_theme_light_surfaceVariant = Color(0xFFE7E0EB)
val md_theme_light_onSurfaceVariant = Color(0xFF49454E)
val md_theme_light_outline = Color(0xFF7A757F)
val md_theme_light_inverseOnSurface = Color(0xFFF5EFF4)
val md_theme_light_inverseSurface = Color(0xFF323033)
val md_theme_light_inversePrimary = Color(0xFFD2BCFF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF6F3DCF)

// dark
val md_theme_dark_primary = Color(0xFFD2BCFF)
val md_theme_dark_onPrimary = Color(0xFF3E008F)
val md_theme_dark_primaryContainer = Color(0xFF571CB6)
val md_theme_dark_onPrimaryContainer = Color(0xFFEADDFF)
val md_theme_dark_secondary = Color(0xFFFFB781)
val md_theme_dark_onSecondary = Color(0xFF4E2600)
val md_theme_dark_secondaryContainer = Color(0xFF6F3800)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFDCC4)
val md_theme_dark_tertiary = Color(0xFFF8ADFB)
val md_theme_dark_onTertiary = Color(0xFF51145A)
val md_theme_dark_tertiaryContainer = Color(0xFF6B2D72)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFD6FD)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1C1B1E)
val md_theme_dark_onBackground = Color(0xFFE6E1E6)
val md_theme_dark_surface = Color(0xFF1C1B1E)
val md_theme_dark_onSurface = Color(0xFFE6E1E6)
val md_theme_dark_surfaceVariant = Color(0xFF49454E)
val md_theme_dark_onSurfaceVariant = Color(0xFFCBC4CF)
val md_theme_dark_outline = Color(0xFF948F99)
val md_theme_dark_inverseOnSurface = Color(0xFF1C1B1E)
val md_theme_dark_inverseSurface = Color(0xFFE6E1E6)
val md_theme_dark_inversePrimary = Color(0xFF6F3DCF)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFD2BCFF)


val seed = Color(0xFF8252E3)
